name: Delete Docker Image

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  remove-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: ${{secrets.TEXAS_MANAGEMENT_ACCOUNT_ID}}.dkr.ecr.eu-west-2.amazonaws.com
      IMAGE_NAME: bs-select-playwright-test
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.TEXAS_NONPROD_ACCOUNT_ID}}:role/bs-select-jenkins-assume-role
          aws-region: eu-west-2
          output-credentials: true

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_REPOSITORY }}

      - name: Delete Docker Image
        run: |
          # Extract the ticket from the branch name

          PR_BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          PR2_BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          BRANCH_NAME="${{ github.ref_name }}"

         

         

