name: Test

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  remove-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest   
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2     

      - name: Test
        run: |
          # Extract the ticket from the branch name

          PR_BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          PR2_BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          BRANCH_NAME="${{ github.ref_name }}"

         

         

